FROM mysql:8.0.12

ENV MYSQL_ROOT_PASSWORD 042006  
ENV MYSQL_DATABASE final_task  
ENV MYSQL_USER avilaqdaniel  
ENV MYSQL_PASSWORD 042006

#command: --default-authentication-plugin=mysql_native_password

ADD init.sql /docker-entrypoint-initdb.d